apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
    version: blue   # Se mantiene en Blue si la validación falla
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
