apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: myapp
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:blue
        ports:
        - containerPort: 80
