name: Simulated EKS Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: echo "Simulación: docker build -t myapp ."

      - name: Push to ECR
        run: echo "Simulación: docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Apply K8s manifests
        run: echo "Simulación: kubectl apply -f k8s/"
