name: Blue-Green EKS Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: echo "docker build -t myapp:green ."

      - name: Push to ECR
        run: echo "docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/myapp:green"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Green version
        run: echo "kubectl apply -f k8s/deployment-green.yaml"

      - name: Health Validation
        run: echo "kubectl rollout status deployment/myapp-deployment-green"

      - name: Switch traffic to Green
        run: echo "kubectl apply -f k8s/service-bluegreen.yaml"
